apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: argocd-ingressroutetcp
  namespace: argocd
spec:
  entryPoints:
    - websecure
  routes:
  - match: HostSNI(`argocd.default`)
    kind: Rule
    services:
    - name: argocd-server
      port: 443
  tls:
    passthrough: true
