# -*- mode: ruby -*-
# vi: set ft=ruby :

login   = "bconchit"
node_ip = "192.168.42.110"

Vagrant.configure("2") do |config|
  config.vm.box     = "generic/centos8"
  config.vm.box_url = "https://app.vagrantup.com/generic/boxes/centos8/versions/3.6.0/providers/virtualbox.box"

  config.vm.synced_folder ".", "/vagrant", disabled: false, create: true

  config.vm.hostname = "#{login}S"
  config.vm.network "private_network", ip: node_ip
  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--name", config.vm.hostname]
    v.customize ["modifyvm", :id, "--memory", 2048]
    v.customize ["modifyvm", :id, "--cpus", 4]
  end
  config.vm.provision "shell", privileged: false, path: "scripts/server.sh", env: {"NODE_IP": node_ip}
  config.vm.provision "shell", privileged: false, path: "scripts/apply.sh"
end
