# -*- mode: ruby -*-
# vi: set ft=ruby :

login   = "bconchit"
node_ip = "192.168.56.110"

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.synced_folder ".", "/vagrant", disabled: false, create: true

  config.vm.hostname = "#{login}S"
  config.vm.network "private_network", ip: node_ip
  config.vm.network "forwarded_port", guest: 6443, host: 6443, protocol: "tcp"

  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--name", config.vm.hostname]
    v.customize ["modifyvm", :id, "--memory", 4096]
    v.customize ["modifyvm", :id, "--cpus", 4]
  end
  config.vm.provision "shell", privileged: false, path: "scripts/server.sh"
end
